apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-login-test
  namespace: argocd
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: argocd-cli
        image: argoproj/argocd:v2.10.2
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Getting ArgoCD password..."
            export PASSWORD=$(kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath="{.data.password}" | base64 -d)
            echo "Logging into ArgoCD..."
            argocd login argocd-server.argocd.svc.cluster.local --grpc-web --insecure --username admin --password "$PASSWORD"
      restartPolicy: Never
