apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-login-test
  namespace: argocd
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: argocd-cli
          image: quay.io/argoproj/argocd:v2.10.2
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Logging into ArgoCD with env password..."
              argocd login argocd-server.argocd.svc.cluster.local \
                --grpc-web \
                --insecure \
                --username admin \
                --password "$ARGOCD_PASSWORD"
          env:
            - name: ARGOCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-initial-admin-secret
                  key: password
      restartPolicy: Never
