apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-login-test
  namespace: argocd
spec:
  template:
    spec:
      serviceAccountName: argocd-server
      containers:
        - name: argocd
          image: argoproj/argocd:latest
          env:
            - name: ARGOCD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-initial-admin-secret
                  key: password
          command:
            - /bin/sh
            - -c
            - |
              echo "Decoded password: $(echo $ARGOCD_PASSWORD | base64 -d)"
              argocd login argocd-server.argocd.svc.cluster.local \
                --insecure --username admin \
                --password $(echo $ARGOCD_PASSWORD | base64 -d) && \
              argocd app list
      restartPolicy: Never