apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-nginx
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx
      version: "15.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    service:
      type: ClusterIP