apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: helm-nginx
  namespace: flux-system
spec:
  interval: 1m
  chart:
    spec:
      chart: ./apps/flux/helm-nginx
      sourceRef:
        kind: GitRepository
        name: local-repo
        namespace: flux-system
