apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-backend
  namespace: default # Или другое пространство имен
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-backend
  template:
    metadata:
      labels:
        app: ui-backend
    spec:
      containers:
      - name: ui-backend
        image: your-docker-repo/ui-backend:latest # Замените на ваш образ
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: production