apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
patches:
  - path: patches/add-last-applied-by-label.yaml
    target:
      kind: Deployment
      name: nginx
